### ISSUE TITLE
PyPI resource fails when using private JFrog artifactory store

### ISSUE THREAD

**Issue by lukeplausin** [cf-platform-eng/concourse-pypi-resource#11]
Hey!

I'm having an issue with the custom resource whereby it fails when trying to retrieve PyPI package metdata after uploading. My Concourse instance returns this stack trace:

```
Output directory: /tmp/build/get
Traceback (most recent call last):
  File "/opt/resource/in", line 9, in <module>
    load_entry_point('concourse-pypi-resource==0.2.0', 'console_scripts', 'in')()
  File "/usr/local/lib/python3.5/site-packages/pypi_resource/in_.py", line 58, in main
    version = in_(destdir, sys.stdin)
  File "/usr/local/lib/python3.5/site-packages/pypi_resource/in_.py", line 47, in in_
    url = pypi.get_pypi_version_url(input, version)
  File "/usr/local/lib/python3.5/site-packages/pypi_resource/pypi.py", line 50, in get_pypi_version_url
    pypi_info = get_pypi_package_info(input)
  File "/usr/local/lib/python3.5/site-packages/pypi_resource/pypi.py", line 39, in get_pypi_package_info
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://<myorg>.jfrog.io/<myorg>/api/pypi/<myteam>/<mypackage>/json
```

I can see that the artifact was uploaded to the store but the job still fails on that step. I couldn't find any documentation on the /json endpoint in JFrog's help pages. Also it looks like the request on that line isn't using any auth hence the 401. I tried in the browser and get a 404.

Is the GET to the json endpoint just to check that the package was really uploaded? Will all repository types feature the endpoint? Is there a way to switch off the check, or could you suggest another solution?

Thanks

**Comment by mboldt** [comment]
Sorry for slow response here. Thank you for your patience.

Yes, concourse always does a `get` after a `put`, presumably to make sure the `put` worked as expected.

I see 2 separate issues here:

1. Authorization: It looks like [you can pass username/password in the URL](https://www.jfrog.com/confluence/display/RTF/PyPI+Repositories#PyPIRepositories-UsingCredentials). Would this work for you? If not, do you know what needs to happen, and could you make a PR for it? (I don't have access to JFrog Artifactory for testing.)

2. JSON: The resource currently uses the [PyPI JSON API](https://wiki.python.org/moin/PyPIJSON). Browsing the JFrog docs, it looks like it only supports the [PyPI Simple API](https://wiki.python.org/moin/PyPISimple). I can make this change if it helps support more private repositories.

Let me know what you think. Thank you!

**Comment by smitt04** [comment]
I am having a similar issue using pypicloud.  My auth works but currently my version doesn't have the json api, only simple.  I am looking at upgrading but I think this would be useful to support older private pypi installations.

**Comment by mboldt** [comment]
I'm happy to take a PR for using the simple API, but I will not likely get around to it myself any time soon.

**Comment by punkadiddle** [comment]
Same with Sonatype Nexus. Also login to private repositories is missing.
It should be mentioned in the docs, that this resource type is limited to the self-published-public-artifact-on-PyPi use case.

I'm working on a fork where I have moved the input/lookup functionality to Pip internal API which can handle all (?) scenarios. Looking at their code there are way more cases thatn Pypi-JSON and one kind of simple index.
Also the python_version parameter is unorthodox. Wheel calls this mixture of packaging, python implementation and python version a tag. Pip and requirements specs use python_version solely for the version of python.

I will do some more testing and documentation within the next days. It would be helpful if someone would be willing to test and comment then.

**Comment by punkadiddle** [comment]
Here's my fork of this resource type. Unfortunately not much left of the original pypi-only implementation. see https://github.com/punkadiddle/concourse-pypi-resource

- Rewritten "check" and "in" to use the current Pip implementation and also the Pip interface and filtering for package selection. There seems to be no golden way about this, but I think it provides the broadest compatibility. There's a risks since listing versions is not a public API on Pip, this binds to a specific Pip version (10.0.1) and might break in the future, at which point a web-page scanner could still written.
- 0.2.0 parameterisation still works (except for repository)
- authorisation also on read operations for private repos (people do use those)
- metadata output on "in"
- tested against private Nexus3 instance (although the examples are written for Nexus there's no Nexus specific code)

**Comment by trulede** [comment]
> I tried the fork from @punkadiddle and it certainly does work for the simple API (I'm using 'pypiserver').
> 
> However, I've noted the following error at the end of a put:
> 
> ```
> Uploading distributions to http://foo:bar@rb-ucp-cc.de.bosch.com:8089
> Uploading sismic-2.0.1.tar.gz
> 100%|██████████| 557k/557k [00:00<00:00, 5.51MB/s]
> Finding package to upload
> Glob PySismic/dist/*.tar.gz matched files: ['/tmp/build/put/PySismic/dist/sismic-2.0.1.tar.gz']
> Uploading /tmp/build/put/PySismic/dist/sismic-2.0.1.tar.gz version 2.0.1
> 
> json: cannot unmarshal string into Go struct field versionResult.version of type atc.Version
> ```
> it works, but Concourse cannot learn the Version that was put ... and at least think the problem might be the return value of the out():
> 
> * cf-platform-eng: `return {'version': {'version': str(version)}}`
> * punkadiddle: `return {'version': response['version']}`
> 
> It seems like the top (seems to be working) version has a nested JSON response, version inside version. I'm still trying to find exactly what atc.Version is (Concourse v4.2.1).

I made the change as mentioned ... and it worked! Currently I'm working with a clone of punkadiddle, I might push that, however, I get the feeling this work should all get combined in one place.

```
version = str(response['version'])
...
return {'version': {'version': version}}
```

**Comment by mboldt** [comment]
Glad you got it working, @trulede! Yeah, would be great to get this all back together in one place. Happy to take a PR of the @punkadiddle fork, or just point folks there as I mentioned above.

Per the [Concourse documentation on implementing a resource](https://concourse-ci.org/implementing-resources.html):

> `version` is a JSON object with string fields, used to uniquely identify an instance of the resource. For git this would be a commit SHA.

So, for the git resource, a `version` looks like:
```
  "version": { "ref": "61cebf" }
```
For something versioned by date, it could look like:
```
  "version": { "date": "2018-10-22" }
```
For PyPI, the unique identifier of an instance is the version number, so we have the version look like:
```
  "version": { "version": "1.2.3" }
```
Hope that helps clarify the nested `version` thing.

**Comment by punkadiddle** [comment]
Do you have time to integrate a pull request? I don't have test setup at the moment and little time - it would be great if some of the work would make it into the main project though.

**Comment by yasn77** [comment]
Hi, 

Just wondering what is happening with this? I am hit by this issue and have to rely on a fork of @punkadiddle repo. But as this repo is linked to concourse community webpage, i would love to be fixed here and not rely on my fork.

I am more than happy to help where I can. Is it simply the case of writing some test? If that's the case and @punkadiddle is busy, I am happy to add some tests to my fork and submit a PR. Would that work?

Thanks

**Comment by trulede** [comment]
I can try to make a PR from my fork (which was taken from punkadiddle). If nobody else has time.

**Comment by mboldt** [comment]
Happy to take a PR.

**Comment by trulede** [comment]
OK, PR  #13 to bring in the changes from punkadiddle.

**Comment by mboldt** [comment]
#13 has been merged and published to `cfplatformeng/concourse-pypi-resource:latest`. Thank you for the contributions!
