### ISSUE TITLE
Allow authentication only for `get` and `check` step

### ISSUE THREAD

**Issue by manuel-pix4d** [cf-platform-eng/concourse-pypi-resource#25]
# New feature request

In case you need to authenticate for the `get` and `check` steps but don't want secret leakage (cf issue https://github.com/cf-platform-eng/concourse-pypi-resource/issues/14), it would be great if we can allow authentication only for `get` and `check` steps.

We are currently hosting an internal PyPi server, an authentication is needed for pulling or checking available artefacts.

We would like to propose a PR for this feature.

**Comment by mboldt** [comment]
With #14 fixed, would you still need this?

**Comment by manuel-pix4d** [comment]
I still need it. When you try to authenticate for `out` or `always` (both `out` and `in_`), then the secrets are passed to the url used by twine. Issue is that this url with encoded secrets is displayed, both in success or failure. We then need a way to enable the authentication only for `in_`.

Let me show you this in the PR.

**Comment by manuel-pix4d** [comment]
Note: I don't know if an authentication in the url is still necessary with `out`, as the creds are passed as environment variable. I let it there to avoid breaking existing pipeline that would use `authenticate: out`.

**Comment by manuel-pix4d** [comment]
ping @mboldt Is there any blocker for this issue ?

**Comment by mboldt** [comment]
#27 merged. Thank you for maintaining backward compatibility with `authenticate: out`. Am working on cutting 0.6.0 release with both of your PRs merged. Thanks again!

**Comment by mboldt** [comment]
This is now live in latest (0.6.0).
