### ISSUE TITLE
Checking availability after uploading a package

### ISSUE THREAD

**Issue by manuel-pix4d** [cf-platform-eng/concourse-pypi-resource#26]
# Feature request

In Concourse, each `put` step is followed by a `get` step. So if you go out from a `put` step, we should make sure that the `get` step can successfully fetch the artefact we produced.

In out infra, we host a PyPi repository from Artifactory and between the upload of an artifact and it's availability, it can take several minutes. We would like to propose a check inside the put task, right after uploading a python library with twine, to make sure the library is available.

We are keen to submit a PR for this feature request.

**Comment by mboldt** [comment]
Yeah, we hit this with public PyPI as well. We put a [retry wrapper](https://github.com/cf-platform-eng/concourse-pypi-resource/blob/a0453cb5741af47229db366d8e04ad3beda9cf73/pypi_resource/in_.py#L50) in the `get` step as a workaround. Could we just make that configurable?

**Comment by manuel-pix4d** [comment]
The issue with this wrapper is that it doesn't raise an error when you don't have any package yet. Hence this failure:
```
Try 1 of 20 to call function `download_version` from module `__main__`
No matching packages found.
Traceback (most recent call last):
  File "/Users/mcastan/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mcastan/.pyenv/versions/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mcastan/code/concourse-pypi-resource/pypi_resource/in_.py", line 107, in <module>
    main()
  File "/Users/mcastan/code/concourse-pypi-resource/pypi_resource/in_.py", line 102, in main
    response = in_(destdir, sys.stdin)
  File "/Users/mcastan/code/concourse-pypi-resource/pypi_resource/in_.py", line 83, in in_
    response['metadata'].update(pkg_info['metadata'])
KeyError: 'metadata'
```

**Comment by manuel-pix4d** [comment]
Like this, we solve the case when no package is there + we make the retry unable, both within the get step alone or when it's combined with put step.

Many thanks for your short replies ! Feel free to ask me more info about the proposed fix.

**Comment by manuel-pix4d** [comment]
ping @mboldt Is there any blocker for this issue ? As we discuss, I did use the retry wrapper in the get step, and making it configurable.

**Comment by mboldt** [comment]
Thanks for the bump on this...I had a long weekend, but back now. #28 merged. Will cut a release after reviewing the other open issue/PR. Thank you!

**Comment by mboldt** [comment]
This is now live in latest (0.6.0).
