### ISSUE TITLE
[New feature] Test in put that input name is identical to uploaded package

### ISSUE THREAD

**Issue by manuel-pix4d** [cf-platform-eng/concourse-pypi-resource#32]
Using twine for uploading the python library, we don't use the `name` as specified in the input of the concourse resource. So if the input `name` is different from the `name` specified in the library, we will successfully do the upload (`put` step) but fail for the download (`get`). We have been caught several time in this issue so in our opinion, it might be wise to check before the upload. Note that if you do it after, you will have the library already there so any retry of download will fail as the library is already in your pypi repo.

I propose to implement a test, in the `put` step before actual upload, that would check that the input `name` is the same as the one specified in the library.

I'm volunteer to propose a PR.

**Comment by mboldt** [comment]
Shoot...I'm second-guessing this after merging. Isn't it pretty common practice to have a project name different than the package name? For example, many project names use hyphens where the python package uses underscores. Or am I missing something here?

**Comment by manuel-pix4d** [comment]
So you would rather want to test that the input name is the same that the project name and not the package name. I'm OK with the change. But for normal case, it's better to stick with 1 common name between package and project, cf https://www.python.org/dev/peps/pep-0423/#use-a-single-name

**Comment by mboldt** [comment]
Thank you for pointing out the best practice documentation. How about keeping the check on by default, but having a flag to disable the check, for packages that a mismatch "for historical reasons" as noted in that doc?

> Note
> For historical reasons, PyPI [11] contains many distributions where project and distributed package/module names differ.

**Comment by manuel-pix4d** [comment]
With a second look, I checked what is the name of the package/project for the concourse resource:
according to the setup.py,
- project name = `concourse-pypi-resource`
- package names = [`pypi_resource`, `test`]

And the test is checking that the package `concourse-pypi-resource` can be correctly fetched, and that `mismatching-name` is not fetched. So I guess that `response['metadata']['package_name']` in [out()](https://github.com/cf-platform-eng/concourse-pypi-resource/blob/3d62b6ae0e72bacaec31cb512836177ec53f770a/pypi_resource/out.py#L74) refers actually to the project name, which is totally confusing I must admit.

That have been said, I'm totally in for this check that can be switched off for these special packages ! Do you mind adding it or do you want that I write a second PR ?

**Comment by mboldt** [comment]
I cam add that and cut a release.

**Comment by mboldt** [comment]
This has been released in 0.7.0. Thank you!
